"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import type { z } from "zod";
import { ArrowRight, BarChart3, Bell, Check, CircleDollarSign, LineChart, Sparkles } from "lucide-react";
import { onboardingSchema } from "@/lib/schemas";
import { useAuth } from "@/lib/auth-context";
import { createAccount, getAccounts, saveOnboarding } from "@/services/journal";
import type { Market, TraderStyle } from "@/types";

type Values=z.infer<typeof onboardingSchema>;
const styles:{value:TraderStyle;description:string}[]=[{value:"Scalper",description:"Seconds to minutes"},{value:"Day trader",description:"Open and close intraday"},{value:"Swing trader",description:"Hold for days or weeks"},{value:"Position trader",description:"Follow longer trends"},{value:"Investor",description:"Build long-term positions"}];
const markets:Market[]=["Crypto","Forex","Futures","Stocks","Options"];

export default function OnboardingPage(){
 const{user,loading}=useAuth();const router=useRouter();const[step,setStep]=useState(1);const[error,setError]=useState("");
 const{register,handleSubmit,watch,setValue,trigger,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(onboardingSchema),defaultValues:{traderStyles:[],markets:[],instruments:"BTC, ETH",experience:"Beginner",baseCurrency:"USD",goal:"Paper trade",emailDigest:false,emailFrequency:"Weekly",accountName:"My trading account",startingBalance:100}});
 useEffect(()=>{if(!loading&&!user)router.replace("/register")},[loading,user,router]);
 const selectedStyles=watch("traderStyles"),selectedMarkets=watch("markets"),digest=watch("emailDigest");
 const toggle=<T extends string>(field:"traderStyles"|"markets",value:T,current:T[])=>setValue(field,[...(current.includes(value)?current.filter(item=>item!==value):[...current,value])] as Values[typeof field],{shouldValidate:true});
 const next=async()=>{const fields:((keyof Values)[]) = step===1?["traderStyles","markets"]:["experience","goal","instruments"];if(await trigger(fields))setStep(value=>Math.min(3,value+1))};
 const submit=async(values:Values)=>{if(!user)return;try{setError("");await saveOnboarding(user.uid,{name:user.displayName||user.email?.split("@")[0],email:user.email||undefined,traderStyles:values.traderStyles,markets:values.markets,instruments:values.instruments.split(",").map(item=>item.trim().toUpperCase()).filter(Boolean),experience:values.experience,baseCurrency:values.baseCurrency,goal:values.goal,emailDigest:values.emailDigest,emailFrequency:values.emailFrequency});if((await getAccounts(user.uid)).length===0)await createAccount(user.uid,{name:values.accountName,balance:values.startingBalance});router.replace("/dashboard")}catch(caught){setError(caught instanceof Error?caught.message:"Could not finish onboarding")}};
 if(loading||!user)return <div className="loading"><span/></div>;
 return <main className="onboarding-page"><div className="onboarding-brand"><span>TT</span><div><strong>Trade Tracker</strong><small>PERSONALIZE YOUR WORKSPACE</small></div></div><div className="onboarding-progress"><div><b style={{width:`${step/3*100}%`}}/></div><span>Step {step} of 3</span></div><form className="onboarding-card" onSubmit={handleSubmit(submit)}>
  {step===1&&<><div className="onboarding-heading"><Sparkles/><small>YOUR TRADING IDENTITY</small><h1>How do you approach the market?</h1><p>Choose everything that fits. You can change this later.</p></div><label className="section-label">TRADING STYLE</label><div className="choice-grid styles">{styles.map(item=><button type="button" key={item.value} className={selectedStyles.includes(item.value)?"selected":""} onClick={()=>toggle("traderStyles",item.value,selectedStyles)}><span>{item.value}</span><small>{item.description}</small>{selectedStyles.includes(item.value)&&<Check/>}</button>)}</div>{errors.traderStyles&&<em className="field-error">{errors.traderStyles.message}</em>}<label className="section-label">MARKETS</label><div className="market-choices">{markets.map(market=><button type="button" key={market} className={selectedMarkets.includes(market)?"selected":""} onClick={()=>toggle("markets",market,selectedMarkets)}>{market}</button>)}</div>{errors.markets&&<em className="field-error">{errors.markets.message}</em>}</>}
  {step===2&&<><div className="onboarding-heading"><BarChart3/><small>YOUR WORKFLOW</small><h1>What should Trade Tracker focus on?</h1><p>We’ll tune your workspace and terminology around these choices.</p></div><div className="form-grid onboarding-fields"><label>Experience<select {...register("experience")}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Professional</option></select></label><label>Primary goal<select {...register("goal")}><option>Paper trade</option><option>Journal real trades</option><option>Track investments</option><option>Improve discipline</option></select></label><label className="span-2">Favorite instruments<input placeholder="BTC, ETH, NQ" {...register("instruments")}/><small>Separate symbols with commas.</small></label></div><div className="onboarding-tip"><LineChart/><div><strong>One profile, flexible workflow</strong><p>An investor can track BTC while also journaling futures or forex trades.</p></div></div></>}
  {step===3&&<><div className="onboarding-heading"><CircleDollarSign/><small>YOUR FIRST ACCOUNT</small><h1>Set your starting point.</h1><p>This can be a real journal balance or fictional paper money.</p></div><div className="form-grid onboarding-fields"><label>Account name<input {...register("accountName")}/></label><label>Base currency<select {...register("baseCurrency")}><option>USD</option><option>EUR</option><option>GBP</option><option>GEL</option></select></label><label className="span-2">Starting balance<input type="number" step="0.01" {...register("startingBalance")}/><small>Use $100 for a small fictional portfolio, or your real account balance.</small></label></div><label className="digest-toggle"><input type="checkbox" {...register("emailDigest")}/><Bell/><span><strong>Email market summary</strong><small>Save your preference now. Email delivery will activate when a provider is connected.</small></span></label>{digest&&<label>Email frequency<select {...register("emailFrequency")}><option>Weekly</option><option>Daily</option></select></label>}</>}
  {error&&<div className="form-error">{error}</div>}<div className="onboarding-actions">{step>1&&<button type="button" className="button ghost" onClick={()=>setStep(value=>value-1)}>Back</button>}{step<3?<button type="button" className="button" onClick={()=>void next()}>Continue <ArrowRight/></button>:<button className="button" disabled={isSubmitting}>{isSubmitting?"Building workspace…":"Enter my dashboard"}<ArrowRight/></button>}</div>
 </form><p className="onboarding-footnote">Your choices personalize the product—they never restrict what you can track.</p></main>
}
