export type Account = { id: string; name: string; balance: number; createdAt: string };
export type Trade = { id: string; accountId: string; balance: number; date: string; weekday: string; session: "Asia"|"London"|"New York"; symbol: string; position: "Long"|"Short"; risk: number; rr: number; pl: number; lots: number; outcome: "Win"|"Loss"|"Break even"; entryTime: string; exitTime: string; emotion: string; preTrade: string; postTrade: string; screenshot: string; createdAt: string; updatedAt: string };
export type TraderStyle = "Scalper" | "Day trader" | "Swing trader" | "Position trader" | "Investor";
export type Market = "Crypto" | "Forex" | "Futures" | "Stocks" | "Options";
export type UserProfile = {
  id: string;
  name: string;
  email: string;
  traderStyles: TraderStyle[];
  markets: Market[];
  instruments: string[];
  experience: "Beginner" | "Intermediate" | "Advanced" | "Professional";
  baseCurrency: "USD" | "EUR" | "GBP" | "GEL";
  goal: "Journal real trades" | "Paper trade" | "Track investments" | "Improve discipline";
  emailDigest: boolean;
  emailFrequency: "Daily" | "Weekly";
  onboardingComplete: boolean;
  createdAt: string;
  updatedAt: string;
};
export type PaperPosition = {
  id: string;
  accountId: string;
  market: Market;
  symbol: string;
  direction: "Long" | "Short";
  entryPrice: number;
  currentPrice: number;
  quantity: number;
  leverage: number;
  openedAt: string;
  thesis: string;
  createdAt: string;
  updatedAt: string;
};
