"use client";
import Link from "next/link";
import {format,isThisMonth,isThisWeek,isToday,parseISO} from "date-fns";
import {ArrowUpRight,BarChart3,BriefcaseBusiness,CircleDollarSign,Percent,Scale,Target,TrendingUp,WalletCards} from "lucide-react";
import {PageTitle} from "@/components/dashboard-shell";
import {useJournal} from "@/hooks/use-journal";
import {useProfile} from "@/hooks/use-profile";
const money=(value:number)=>`${value<0?"-":""}$${Math.abs(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function Dashboard(){
 const{accounts,trades,loading,error}=useJournal();const{profile}=useProfile();const pl=trades.reduce((sum,trade)=>sum+trade.pl,0);const wins=trades.filter(trade=>trade.outcome==="Win");const losses=trades.filter(trade=>trade.outcome==="Loss");const grossWin=wins.reduce((sum,trade)=>sum+Math.max(0,trade.pl),0);const grossLoss=Math.abs(losses.reduce((sum,trade)=>sum+Math.min(0,trade.pl),0));
 const cards=[{label:"Current balance",value:money(accounts.reduce((sum,account)=>sum+account.balance,0)+pl),icon:WalletCards},{label:"Today’s P/L",value:money(trades.filter(trade=>isToday(parseISO(trade.date))).reduce((sum,trade)=>sum+trade.pl,0)),icon:CircleDollarSign},{label:"Weekly P/L",value:money(trades.filter(trade=>isThisWeek(parseISO(trade.date))).reduce((sum,trade)=>sum+trade.pl,0)),icon:TrendingUp},{label:"Monthly P/L",value:money(trades.filter(trade=>isThisMonth(parseISO(trade.date))).reduce((sum,trade)=>sum+trade.pl,0)),icon:BarChart3},{label:"Total trades",value:String(trades.length),icon:Target},{label:"Win rate",value:`${trades.length?(wins.length/trades.length*100).toFixed(1):0}%`,icon:Percent},{label:"Average RR",value:`${trades.length?(trades.reduce((sum,trade)=>sum+trade.rr,0)/trades.length).toFixed(2):0}R`,icon:Scale},{label:"Profit factor",value:grossLoss?(grossWin/grossLoss).toFixed(2):grossWin?"∞":"0.00",icon:ArrowUpRight}];
 const name=profile?.name?.split(" ")[0]||"trader";const hasPositionWorkflow=profile?.traderStyles?.some(style=>style==="Investor"||style==="Position trader");const focus=hasPositionWorkflow?"investment decisions":"trading discipline";
 return <div className="page"><PageTitle eyebrow={`${profile?.traderStyles?.join(" · ")||"PERSONALIZED"} WORKSPACE`} title={`Welcome back, ${name}.`} description={`Here’s how your ${focus} are translating into results.`}/>{error&&<div className="notice">{error}</div>}<div className="dashboard-focus"><div><small>YOUR FOCUS</small><strong>{profile?.goal||"Build consistency"}</strong><p>{profile?.markets?.join(" · ")} · {profile?.instruments?.join(", ")}</p></div>{hasPositionWorkflow?<Link href="/dashboard/portfolio"><BriefcaseBusiness/><span><b>Paper portfolio</b><small>Practice with fictional money and leverage</small></span><ArrowUpRight/></Link>:<Link href="/dashboard/trades?new=1"><BarChart3/><span><b>Log an execution</b><small>Record risk, result, and trading notes</small></span><ArrowUpRight/></Link>}</div><div className="stats-grid">{cards.map(({label,value,icon:Icon})=><article className="stat-card" key={label}><div><span>{label}</span><strong>{loading?"—":value}</strong></div><Icon/></article>)}</div><section className="panel"><div className="panel-head"><div><small>LAST 5 EXECUTIONS</small><h3>Recent trades</h3></div><Link href="/dashboard/trades">View all <ArrowUpRight/></Link></div>{trades.length?<div className="trade-list">{trades.slice(0,5).map(trade=><div key={trade.id}><span className={`side ${trade.position.toLowerCase()}`}>{trade.position.slice(0,1)}</span><strong>{trade.symbol}</strong><span>{format(parseISO(trade.date),"MMM d, yyyy")}</span><span>{accounts.find(account=>account.id===trade.accountId)?.name||"Account"}</span><b className={trade.pl>=0?"positive":"negative"}>{money(trade.pl)}</b></div>)}</div>:<div className="mini-empty">Your latest executions will appear here. <Link href="/dashboard/trades?new=1">Log your first trade</Link></div>}</section></div>;
}
